### PR TITLE
Turn off rspec coverage reports

### PR DESCRIPTION
**Pull request by rshipp**
### Description

Stop running Simplecov entirely, until we (hopefully) get some support from Heroku or figure out why this is failing. 

### Motivation and Context

Having coverage reports is not worth losing CI.

### Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

### Checklist:

- [ ] My code follows the code style of this project.
- [ ] I have added neccessary labels
- [ ] My PR title follows the convention in the guide
- [ ] I have assigned myself to the PR
- [ ] I have requested reviews from team members
- [ ] I have created a task for reviewers on PM tool
- [ ] All new and existing tests passed.

### CODE REVIEW

**Review by sadleb — APPROVED** [review]
Fingers crossed!

**Comment by rshipp** [comment]
Didn't work.

**Review by sadleb — APPROVED** [review]
Ugh, this stinks, but yeah. The CI situation is worse than losing this for now. Just make sure and queue up a task to revisit and try to fix (hopefully with Heroku support).

**Comment by rshipp** [comment]
Closing, since this didn't seem to fix anything.

**Pull request closed without merging**
